[theme]
# Primary accent color for interactive elements.
primarColor = "#d33682"

# base="dark"

# Background color for the main content area.
backgroundColor = "#010000"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#5FF4B4B"

# Color used for almost all text.
textColor = "#fff"

[client]
# Controls whether the default sidebar page navigation in a multipage app is
# displayed.
# Default: true
showSidebarNavigation = false